# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.update_qh = QtWidgets.QPushButton(self.centralwidget)
        self.update_qh.setGeometry(QtCore.QRect(260, 560, 271, 28))
        self.update_qh.setObjectName("update_qh")
        self.qhlogo = QtWidgets.QLabel(self.centralwidget)
        self.qhlogo.setGeometry(QtCore.QRect(200, 40, 441, 101))
        self.qhlogo.setMinimumSize(QtCore.QSize(441, 101))
        self.qhlogo.setText("")
        self.qhlogo.setScaledContents(True)
        self.qhlogo.setObjectName("qhlogo")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(150, 210, 411, 213))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(411, 213))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.islands_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.islands_pyqt.setObjectName("islands_pyqt")
        self.gridLayout_2.addWidget(self.islands_pyqt, 1, 0, 1, 1)
        self.ribbons_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.ribbons_pyqt.setObjectName("ribbons_pyqt")
        self.gridLayout_2.addWidget(self.ribbons_pyqt, 2, 0, 1, 1)
        self.heterostructure = QtWidgets.QPushButton(self.tab_3)
        self.heterostructure.setObjectName("heterostructure")
        self.gridLayout_2.addWidget(self.heterostructure, 4, 1, 1, 1)
        self.hofstader_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.hofstader_pyqt.setObjectName("hofstader_pyqt")
        self.gridLayout_2.addWidget(self.hofstader_pyqt, 10, 0, 1, 1)
        self.film2d_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.film2d_pyqt.setObjectName("film2d_pyqt")
        self.gridLayout_2.addWidget(self.film2d_pyqt, 4, 0, 1, 1)
        self.huge0d_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.huge0d_pyqt.setObjectName("huge0d_pyqt")
        self.gridLayout_2.addWidget(self.huge0d_pyqt, 1, 1, 1, 1)
        self.crystal3d_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.crystal3d_pyqt.setObjectName("crystal3d_pyqt")
        self.gridLayout_2.addWidget(self.crystal3d_pyqt, 10, 1, 1, 1)
        self.hybridribbon_pyqt = QtWidgets.QPushButton(self.tab_3)
        self.hybridribbon_pyqt.setObjectName("hybridribbon_pyqt")
        self.gridLayout_2.addWidget(self.hybridribbon_pyqt, 2, 1, 1, 1)
        self.sheets = QtWidgets.QPushButton(self.tab_3)
        self.sheets.setObjectName("sheets")
        self.gridLayout_2.addWidget(self.sheets, 3, 0, 1, 1)
        self.twisted_bilayer = QtWidgets.QPushButton(self.tab_3)
        self.twisted_bilayer.setObjectName("twisted_bilayer")
        self.gridLayout_2.addWidget(self.twisted_bilayer, 3, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 0, 200, 302))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.skyrmion = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.skyrmion.setObjectName("skyrmion")
        self.gridLayout.addWidget(self.skyrmion, 6, 0, 1, 1)
        self.moire = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.moire.setObjectName("moire")
        self.gridLayout.addWidget(self.moire, 8, 0, 1, 1)
        self.ribbons = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ribbons.setObjectName("ribbons")
        self.gridLayout.addWidget(self.ribbons, 2, 0, 1, 1)
        self.huge_islands = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.huge_islands.setObjectName("huge_islands")
        self.gridLayout.addWidget(self.huge_islands, 7, 0, 1, 1)
        self.vacancy2d = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.vacancy2d.setObjectName("vacancy2d")
        self.gridLayout.addWidget(self.vacancy2d, 9, 0, 1, 1)
        self.islands = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.islands.setObjectName("islands")
        self.gridLayout.addWidget(self.islands, 0, 0, 1, 1)
        self.multilayers = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.multilayers.setObjectName("multilayers")
        self.gridLayout.addWidget(self.multilayers, 1, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 170, 331, 18))
        self.label.setObjectName("label")
        self.qh_version = QtWidgets.QLabel(self.centralwidget)
        self.qh_version.setGeometry(QtCore.QRect(110, 600, 181, 41))
        self.qh_version.setText("")
        self.qh_version.setObjectName("qh_version")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quantum Honeycomp: system selection"))
        self.update_qh.setToolTip(_translate("MainWindow", "This command will download the latest version fo Quantum Honeycomp from github"))
        self.update_qh.setText(_translate("MainWindow", "Update Quantum Honeycomp"))
        self.islands_pyqt.setText(_translate("MainWindow", "Islands"))
        self.ribbons_pyqt.setText(_translate("MainWindow", "Ribbons"))
        self.heterostructure.setText(_translate("MainWindow", "Hybrid films"))
        self.hofstader_pyqt.setText(_translate("MainWindow", "Hofstader butterflies"))
        self.film2d_pyqt.setText(_translate("MainWindow", "Films"))
        self.huge0d_pyqt.setText(_translate("MainWindow", "Huge islands"))
        self.crystal3d_pyqt.setText(_translate("MainWindow", "3D crystals"))
        self.hybridribbon_pyqt.setText(_translate("MainWindow", "Hybrid ribbons"))
        self.sheets.setText(_translate("MainWindow", "Sheets"))
        self.twisted_bilayer.setText(_translate("MainWindow", "Twisted bilayer"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Linux and MacOSX compatible"))
        self.skyrmion.setText(_translate("MainWindow", "Skyrmion in 2D"))
        self.moire.setText(_translate("MainWindow", "Moire potential 2D"))
        self.ribbons.setText(_translate("MainWindow", "Ribbons"))
        self.huge_islands.setText(_translate("MainWindow", "Colossal islands"))
        self.vacancy2d.setText(_translate("MainWindow", "Vancancies in 2D"))
        self.islands.setText(_translate("MainWindow", "Islands"))
        self.multilayers.setText(_translate("MainWindow", "Honeycomb multilayers"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "Only Linux compatible"))
        self.label.setText(_translate("MainWindow", "Select the system you want to compute"))

