#!/usr/bin/python
from __future__ import print_function

# this script installs the quantum honeycomp package
import os
import sys

pwd = os.getcwd() # get the current location

# compile f2py routines
os.chdir(pwd)
os.system("python compile_fortran.py") # compile fortran programs


os.chdir(pwd+'/bin') # go to bin directory
os.system('chmod +x quantum-honeycomp*')   # give execution permission

os.chdir(pwd) # go to the main directory
os.system("python addsystem.py") # add the route to the .bashrc
