# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'islands.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(328, 290, 471, 261))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(50, 30, 238, 80))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.lattice = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.lattice.setObjectName("lattice")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.lattice.addItem("")
        self.gridLayout_4.addWidget(self.lattice, 0, 1, 1, 1)
        self.geometry_dimensionality = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.geometry_dimensionality.setObjectName("geometry_dimensionality")
        self.geometry_dimensionality.addItem("")
        self.geometry_dimensionality.addItem("")
        self.geometry_dimensionality.addItem("")
        self.geometry_dimensionality.addItem("")
        self.gridLayout_4.addWidget(self.geometry_dimensionality, 1, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 229, 160))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.size = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.size.setObjectName("size")
        self.gridLayout_3.addWidget(self.size, 0, 1, 1, 1)
        self.nedges = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.nedges.setObjectName("nedges")
        self.gridLayout_3.addWidget(self.nedges, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.rotation = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.rotation.setObjectName("rotation")
        self.gridLayout_3.addWidget(self.rotation, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_9)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(40, 60, 261, 100))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        self.ribbon_type = QtWidgets.QComboBox(self.gridLayoutWidget_6)
        self.ribbon_type.setObjectName("ribbon_type")
        self.ribbon_type.addItem("")
        self.ribbon_type.addItem("")
        self.ribbon_type.addItem("")
        self.gridLayout_6.addWidget(self.ribbon_type, 1, 1, 1, 1)
        self.ribbon_width = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.ribbon_width.setObjectName("ribbon_width")
        self.gridLayout_6.addWidget(self.ribbon_width, 0, 1, 1, 1)
        self.ribbon_supercell = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.ribbon_supercell.setObjectName("ribbon_supercell")
        self.gridLayout_6.addWidget(self.ribbon_supercell, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidget.addTab(self.tab_13, "")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 20, 251, 431))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 201, 356))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.Bz = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Bz.setObjectName("Bz")
        self.gridLayout.addWidget(self.Bz, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.By = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.By.setObjectName("By")
        self.gridLayout.addWidget(self.By, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.hopping = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.hopping.setObjectName("hopping")
        self.gridLayout.addWidget(self.hopping, 0, 1, 1, 1)
        self.Bx = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Bx.setObjectName("Bx")
        self.gridLayout.addWidget(self.Bx, 3, 1, 1, 1)
        self.rashba = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.rashba.setObjectName("rashba")
        self.gridLayout.addWidget(self.rashba, 6, 1, 1, 1)
        self.mAB = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mAB.setObjectName("mAB")
        self.gridLayout.addWidget(self.mAB, 8, 1, 1, 1)
        self.kanemele = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.kanemele.setObjectName("kanemele")
        self.gridLayout.addWidget(self.kanemele, 7, 1, 1, 1)
        self.mAF = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.mAF.setObjectName("mAF")
        self.gridLayout.addWidget(self.mAF, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.peierls = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.peierls.setObjectName("peierls")
        self.gridLayout.addWidget(self.peierls, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_3.setGeometry(QtCore.QRect(300, 50, 491, 161))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.show_structure = QtWidgets.QPushButton(self.tab_4)
        self.show_structure.setGeometry(QtCore.QRect(20, 20, 188, 28))
        self.show_structure.setObjectName("show_structure")
        self.tabWidget_3.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.show_bands = QtWidgets.QPushButton(self.tab_5)
        self.show_bands.setGeometry(QtCore.QRect(20, 30, 188, 28))
        self.show_bands.setObjectName("show_bands")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_5)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 70, 168, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.bands_color = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.bands_color.setObjectName("bands_color")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.bands_color.addItem("")
        self.gridLayout_2.addWidget(self.bands_color, 0, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.show_dos = QtWidgets.QPushButton(self.tab_6)
        self.show_dos.setGeometry(QtCore.QRect(50, 40, 188, 28))
        self.show_dos.setObjectName("show_dos")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_6)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(90, 80, 160, 32))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.DOS_smearing = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.DOS_smearing.setObjectName("DOS_smearing")
        self.gridLayout_5.addWidget(self.DOS_smearing, 0, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 40, 188, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.initialize = QtWidgets.QPushButton(self.tab_8)
        self.initialize.setGeometry(QtCore.QRect(70, 50, 188, 28))
        self.initialize.setObjectName("initialize")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_10)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(110, 10, 160, 98))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.show_berry2d = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.show_berry2d.setObjectName("show_berry2d")
        self.gridLayout_7.addWidget(self.show_berry2d, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_7.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_10, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.geometry_dimensionality.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(5)
        self.bands_color.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Type of lattice"))
        self.lattice.setItemText(0, _translate("MainWindow", "Honeycomb"))
        self.lattice.setItemText(1, _translate("MainWindow", "Square"))
        self.lattice.setItemText(2, _translate("MainWindow", "Triangular"))
        self.lattice.setItemText(3, _translate("MainWindow", "Kagome"))
        self.lattice.setItemText(4, _translate("MainWindow", "Lieb"))
        self.geometry_dimensionality.setItemText(0, _translate("MainWindow", "Island (0D)"))
        self.geometry_dimensionality.setItemText(1, _translate("MainWindow", "Ribbon (1D)"))
        self.geometry_dimensionality.setItemText(2, _translate("MainWindow", "Sheet (2D)"))
        self.geometry_dimensionality.setItemText(3, _translate("MainWindow", "Crystal (3D)"))
        self.label_20.setText(_translate("MainWindow", "Dimensionality"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Geometry"))
        self.label_6.setText(_translate("MainWindow", "Size"))
        self.size.setText(_translate("MainWindow", "4"))
        self.nedges.setText(_translate("MainWindow", "3"))
        self.label_7.setText(_translate("MainWindow", "Number of edges"))
        self.label_9.setText(_translate("MainWindow", "Rotation"))
        self.rotation.setText(_translate("MainWindow", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Islands"))
        self.label_19.setText(_translate("MainWindow", "Supercell"))
        self.label_18.setText(_translate("MainWindow", "Type"))
        self.label_17.setText(_translate("MainWindow", "Width"))
        self.ribbon_type.setItemText(0, _translate("MainWindow", "Honeycomb zigzag"))
        self.ribbon_type.setItemText(1, _translate("MainWindow", "Honeycomb armchair"))
        self.ribbon_type.setItemText(2, _translate("MainWindow", "Square"))
        self.ribbon_width.setText(_translate("MainWindow", "10"))
        self.ribbon_supercell.setText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), _translate("MainWindow", "Ribbon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Sheet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "Bulk"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Sculpt"))
        self.label_5.setText(_translate("MainWindow", "Zeeman Jz"))
        self.Bz.setText(_translate("MainWindow", "0.0"))
        self.label_13.setText(_translate("MainWindow", "Antiferromagnetism"))
        self.label_4.setText(_translate("MainWindow", "Zeeman Jy"))
        self.label_2.setText(_translate("MainWindow", "Antiferromagnetism"))
        self.label_3.setText(_translate("MainWindow", "Zeeman Jx"))
        self.By.setText(_translate("MainWindow", "0.0"))
        self.label.setText(_translate("MainWindow", "Hopping"))
        self.lineEdit_2.setText(_translate("MainWindow", "0.0"))
        self.hopping.setText(_translate("MainWindow", "1.0"))
        self.Bx.setText(_translate("MainWindow", "0.0"))
        self.rashba.setText(_translate("MainWindow", "0.0"))
        self.mAB.setText(_translate("MainWindow", "0.0"))
        self.kanemele.setText(_translate("MainWindow", "0.0"))
        self.mAF.setText(_translate("MainWindow", "0.0"))
        self.label_10.setText(_translate("MainWindow", "Rashba"))
        self.label_11.setText(_translate("MainWindow", "Kane-Mele"))
        self.label_12.setText(_translate("MainWindow", "Sublattice imbalance"))
        self.label_14.setText(_translate("MainWindow", "Magnetic field"))
        self.peierls.setText(_translate("MainWindow", "0.0"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Terms in the Hamiltonian"))
        self.show_structure.setText(_translate("MainWindow", "Structure"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_4), _translate("MainWindow", "Structure"))
        self.show_bands.setText(_translate("MainWindow", "Band structure"))
        self.label_15.setText(_translate("MainWindow", "Operator"))
        self.bands_color.setItemText(0, _translate("MainWindow", "None"))
        self.bands_color.setItemText(1, _translate("MainWindow", "Sx"))
        self.bands_color.setItemText(2, _translate("MainWindow", "Sy"))
        self.bands_color.setItemText(3, _translate("MainWindow", "Sz"))
        self.bands_color.setItemText(4, _translate("MainWindow", "Valley"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Bands"))
        self.show_dos.setText(_translate("MainWindow", "Density of states"))
        self.label_16.setText(_translate("MainWindow", "Smearing"))
        self.DOS_smearing.setText(_translate("MainWindow", "0.01"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "DOS"))
        self.pushButton_4.setText(_translate("MainWindow", "Local density of states"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "LDOS"))
        self.initialize.setText(_translate("MainWindow", "Initialize"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "SCF"))
        self.show_berry2d.setText(_translate("MainWindow", "Berry curvature"))
        self.pushButton.setText(_translate("MainWindow", "Z2 invariant"))
        self.pushButton_2.setText(_translate("MainWindow", "Chern number"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Topology 2D"))

