#!/usr/bin/python2

# this script installs the quantum honeycomp package,
# it will ask for sudo permission to install python libraries

# if you prefer an instalation that do not requires sudo,
# use the install script






######################################################



f90src = "f90src"  # fortran 90 source

import os

if "ubuntu" in open("/proc/version").read():   # autoinstall for ubuntu
  os.system("install_dependencies/autoinstall_ubuntu") 


# compile the program
import subprocess

print "Compiling...."

pwd = os.getcwd()

# compile f2py routines
os.chdir(pwd+"/pysrc")
os.system("python compile_fortran.py") # compile fortran programs
os.chdir("..")


# compile tb90.x
os.chdir(pwd+"/"+f90src) # go to srcf90
os.system('chmod +x compilation.sh')  # compile 
os.system("rm tb90.x ")
os.system('./compilation.sh')  # compile 
if os.path.isfile("tb90.x"):
  print "Successful compilation"
else:
  print "Compilation failed, check the file compilation.sh"
  sys.exit()  





# copy programs to the bin directory
os.chdir(pwd+'/bin') # go to bin directory
os.system('cp '+pwd+'/utilities/* '+pwd+'/bin') # copy utilities
os.system('cp '+pwd+"/"+f90src+"/tb90.x "+pwd+"/bin") # copy tb90.x
fx = open('qhroot.py','w')
fx.write('path='+"'"+pwd+"/files'\n")
fx.close()
os.system('chmod +x *')   # give execution permission

print "Done!\n"

print "Added to your .bashrc\n\n"


line = "\n\nexport PATH=$PATH:"+pwd+"/bin\n\n\n"
os.system("echo '"+line+"'  >>~/.bashrc") # add to bashrc
print line # line in the bashrc


