#!/usr/bin/python

import numpy as np
import numpy 

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--nx",default=50)
parser.add_argument("--ny",default=50)
#        description="Frames per second in the video")
args = parser.parse_args() # get the arguments



def write_interpolation(centers=[[0.,0.,0.]], heights=[10.0],name=""):
    """ Creates a set of lorentzian at that position and with a height"""
    if len(heights)<len(centers):
      heights = [10. for i in centers]
    fac = 5.0 # factor to mix the gaussians
    def wave(x,y):
      z = 0.
      for (c,h) in zip(centers,heights):
        r = ((x-c[0])**2+(y-c[1])**2)*fac # renormalized gaussian       
        z += h*np.exp(-(r))-c[2]
      return z+1.0
    xs = [c[0] for c in centers] # get x coordinates
    ys = [c[1] for c in centers] # get y coordinates
    dxy = (max(xs) - min(xs))/200
    x = np.linspace(min(xs),max(xs),args.nx)
    y = np.linspace(min(ys),max(ys),args.ny)
    fo = open(name,"w") # open output file
    for ix in x:
      for iy in y:
        iz = wave(ix,iy)
        fo.write(str(ix)+"    ")
        fo.write(str(iy)+"    ")
        fo.write(str(iz)+"\n")
    fo.close()

#centers = np.arange(0.,10.,2.)

import sys
# get the centers of the balls
try:
  name = sys.argv[1]
except:
  print("Usage qh-interpolate name")
  exit() # exit
m = np.genfromtxt(name).transpose()

centers = [[m[0,i],m[1,i],0.] for i in range(len(m[0]))]

heights = m[2]
#heights = read_density()
heights = 4*heights/max(heights)
#heights = np.sqrt(heights)
#balls = [ball(center=c) for c in centers]



write_interpolation(centers=centers,heights=heights,name=name+"-interpolated")



