#!/usr/bin/python

import numpy as np
import numpy 

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--input",default="")
parser.add_argument("--nx",default=4)
parser.add_argument("--ny",default=4)
#        description="Frames per second in the video")
args = parser.parse_args() # get the arguments
nx = int(args.nx)
ny = int(args.ny)

name = args.input



if name=="":
    print("Provide an input file")
    exit()

m = np.genfromtxt(name).T # get data
x0 = m[0]
y0 = m[1]

# now interpolate everything
x = np.unique(x0) # array with x
y = np.unique(y0) # array with y
nx0 = len(x)
ny0 = len(y)
xn = np.linspace(np.min(x),np.max(x),nx0*nx,endpoint=True)
yn = np.linspace(np.min(y),np.max(y),ny0*ny,endpoint=True)

xn2d = []
yn2d = []
for ix in xn:
  for iy in yn:
      xn2d.append(ix)
      yn2d.append(iy)


from scipy.interpolate import interp2d

def refine(i):
  z = m[2+i].reshape((nx0,ny0))
  f = interp2d(x,y,z,kind="quintic")
  out = f(xn,yn)
  return out.reshape(nx0*ny0*nx*ny)

out = [xn2d,yn2d] + [refine(i) for i in range(len(m)-2)]

np.savetxt("INTERPOLATED_"+name,np.array(out).T)



