#!/usr/bin/python

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys

# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})

fig = plt.figure()

fig.set_facecolor("white") # white

name = sys.argv[1] # name of the file

m = np.genfromtxt(name).transpose() # read file
x1 = m[0] # x position
y1 = m[1] # y position
x2 = m[2] # z position
y2 = m[3] # z position
ts = m[4] # weight of the link

tm = np.mean(ts) # average

for i in range(len(x1)): # loop over pairs
  x = [x1[i],x2[i]]
  y = [y1[i],y2[i]]
  if ts[i]<tm:
    plt.plot(x,y,c="red",linewidth=ts[i]*2)
  else:
    plt.plot(x,y,c="blue",linewidth=ts[i]*2)

plt.scatter(x1,y1,color="black",s=200)
plt.scatter(x2,y2,color="black",s=200)



plt.xticks([])
plt.yticks([])

plt.axis("equal")
plt.show()
