#!/usr/bin/python

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys

# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})

fig = plt.figure()

fig.set_facecolor("white") # white

name = sys.argv[1] # name of the file

m = np.genfromtxt(name).transpose() # read file
x = m[0] # x position
y = m[1] # y position
z = m[2] # z position



size = 500./np.sqrt(len(z))
#size = 100

plt.title(str(len(x))+" atoms")
plt.scatter(x,y,color="black",s=size)
plt.xticks([])
plt.yticks([])


for i in range(len(x)):
  for j in range(i,len(x)):
    dd = (x[i] -x[j])**2 + (y[i] -y[j])**2
    if 0.1<dd<1.01:
      plt.plot([x[i],x[j]],[y[i],y[j]],c="black")



plt.axis("equal")
plt.show()
