#!/usr/bin/python2

from __future__ import print_function
import numpy as np

try:
  from mayavi import mlab
except:
  print("Mayavi not present in python3, trying python2")
  try: 
    import os
    qhpath = os.environ["QHROOT"]+"/" # path to quantum honeycomp
    os.system("/usr/bin/python2.7 "+qhpath+"utilities/qh-structure-tbg")
  except:
    print("Something wrong")
    exit()
  exit()


################################################################################
# Disable the rendering, to get bring up the figure quicker:
mlab.figure(1, fgcolor=(0, 0, 0), bgcolor=(1, 1, 1))
figure = mlab.gcf()
mlab.clf()
figure.scene.disable_render = True

# Creates two set of points using mlab.points3d: red point and
# white points



def read_positions():
  """Reads the positions of the system"""
  return np.genfromtxt("POSITIONS.OUT").transpose()


(x1,y1,z1) = read_positions()


xu,yu,zu = [],[],[]  # upper layer
xl,yl,zl = [],[],[]  # lower layer

for (ix,iy,iz) in zip(x1,y1,z1): # loop
  if iz<0.0:
    xu.append(ix)
    yu.append(iy)
    zu.append(iz)
  else:
    xl.append(ix)
    yl.append(iy)
    zl.append(iz)


mlab.points3d(xu, yu, zu, color=(1, 0, 0), scale_factor = .8,
                resolution=10)
mlab.points3d(xl, yl, zl, color=(0, 0, 1), scale_factor = .8,
                resolution=10)
print("AAAAAAAAAAAAAA")


# Every object has been created, we can reenable the rendering.
figure.scene.disable_render = False
################################################################################



mlab.show()
