#!/usr/bin/python

import pylab as py
import numpy as np
import sys

fig = py.figure()
fig.set_facecolor("white") # white face

m = py.genfromtxt("BERRY_CURVATURE.OUT").transpose() # get the curvature

m[2] /= 2.*np.pi

chern = sum(m[2])/len(m[2])
achern = sum(np.abs(m[2]))

print("Chern number is",chern)
print("Absolute Chern number is",achern/(len(m[2])))

if "half" in sys.argv:
  b = m[2]
  bh = []
  x = m[0]
  xm = (max(x)+min(x))/2.0
  for i in range(len(x)):
    if x[i]>xm:
      bh.append(b[i])
  hchern = sum(bh)
  print("Half Chern number is",hchern/(len(bh)))

fw = open("CHERN.OUT","w")
fw.write(str(int(np.round(chern,0)))) # write chern number
fw.close()


