#!/usr/bin/python

from __future__ import print_function
import numpy as np
import matplotlib.pyplot as plt
import sys

# change the font size
import matplotlib
matplotlib.rcParams.update({'font.size': 18})


### script for ploting BANDS.OUT of tb90 ###


from os import system as sh


def plot_bands():
  """ Plots the bandstructure from BANDS.OUT"""
    
  def onpick3(event):
      ind = event.ind
      kwave = np.take(k, ind)[0]
      ewave = np.take(e, ind)[0]
      print(kwave,ewave)
      sh("tb90-wave "+str(kwave)+" "+str(ewave)+"&")
      print('onpick3 scatter:', ind, np.take(k, ind), np.take(e, ind))
              
  fig = plt.figure()
  
  
  
  fig.subplots_adjust(0.2,0.2)
  
  ### find the dimension of the system ###
  def system_dimension(f):
    lines = open(f,"r")
    for l in lines:
      if "system_dimension" in l:
        d = int(l.split("=")[1])
        return d
  
  
  # check if shift the bands by 0.5
  
  shift_k=False
  if "-c" in sys.argv:
    shift_k=True
  
  
  
  # the color map
  import numpy as np
  cdict={'red': ((0., 0, 0),(0.6,0.0,0.0),(1, 1.0, 1.0)), 'green': ((0., 0.0, 0.0),(0.4,1.0,1.0),(0.6,1.0,1.0),(1, 0.0, 0.0)), 'blue': ((0., 1.0, 1.0),(0.4,0.0,0.0), (1, 0.0, 0.0))}
  import matplotlib
  my_cmap = matplotlib.colors.LinearSegmentedColormap('my_colormap',cdict,256)
  
  
  
  
  
  
  
  m = np.genfromtxt("BANDS.OUT").transpose()
  # get the dimension
  dimension = system_dimension("BANDS.OUT")
  
  
  # check if plot the color
  draw_color = False
  if len(m.T[0]) > 2:
    draw_color = True
    color = m[2]
  
  # plot in black
  if "-bw" in sys.argv:
    draw_color = False
  
  
  
  
  k = m[0] # default x axis
  xlabel = "K-path" # default
  if dimension==0: xlabel = "Eigenvalue number"  # default xlabel
  if dimension==1: xlabel = "$k/(2\pi)$"  # default xlabel
  if dimension!=0: k = (k-min(k))/float(max(k)-min(k))
  if "-1d" in sys.argv: # if one dimensional, take from input
    k = np.genfromtxt("KPOINTS_BANDS.OUT").transpose()[1]
    print("One dimensional bandstructure")
    xlabel = "$k/(2\pi)$"
  if "-0d" in sys.argv: # if one dimensional, take from input
    k = m[0]
    print("Zero dimensional system, set of eigenvalues")
    xlabel = "Eigenvalue #"
  e = m[1]
  if shift_k:
    k = (k+0.5)%1.0
  
  # plot a rectangle in the ocupied levels
  from matplotlib.patches import Rectangle
  plt.fill_between(sorted(k),min(e),0,color="yellow")
  
  if not draw_color:  # plot without color
    col = plt.scatter(k,e, color ="black")
  if draw_color: # plot with color
    col = plt.scatter(k,e,c=color,cmap=my_cmap, color ="black" ,edgecolors='none')
  plt.xlim([min(k),max(k)])   # x axis range
  plt.ylim([min(e),max(e)])   # y axis range
  
  
  # axis
  xlab = plt.xlabel(xlabel) # lbel of the x axis
  ylab = plt.ylabel("$E/t$")
  # font size of the axis
  ylab.set_fontsize(30) # label of the y xis
  xlab.set_fontsize(30) # label of the y xis
  fig.set_facecolor("white")  # set the layout in white
  if "-noshow" in sys.argv:
    plt.savefig("BANDS.png")
  bandstructure = plt.gcf()
  bandstructure.canvas.set_window_title('Bandstructure')
# add the lines in the bandstructure
  if "label" in sys.argv:
    ll = open("BANDLINES.OUT","r").readlines()
    ik = []
    names = []
    for l in ll:
      l = l.split()
      ik.append(float(l[0]))
      names.append("$"+l[1]+"$")
    ik = np.array(ik)/max(ik)
    plt.xticks(ik,names)

  return fig


if __name__=="__main__":
  fig = plot_bands()  
  if not "-noshow" in sys.argv:
    plt.show()
