gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c io_files.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c inputs.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c sparse.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c system_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c expectation_values_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c sintax_hamiltonian.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c bands_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c mean_field_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c berry_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c save_mf_routines.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c offdiagonal.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c dielectric_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c expectation_values_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c dos_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c system_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c density_matrix_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c berry_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c mean_field_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c bands_variables.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvalues_ewindow.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c diagonalize_collinear.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvalues.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c invert_matrix.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c density_matrix.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvectors_kpoint.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c inputs.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c setup_mixing.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c diagonalize.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c offdiagonal.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c new_mfham_collinear.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c get_klist.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c read_mf_op.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c sort_absolute.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c kwaves.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c selfconsistency.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c dielectric_operators.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c all_eigen.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c mixing.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c all_eigenvalues.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c save_mf_routines.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvalues_kpoint.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvectors.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c occupations.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvalues_z.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c det.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c sparse.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c read_hamil.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c green_machinery.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigen_scf.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c sintax_hamiltonian.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c noncolinear_routines.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c eigenvectors_ewindow.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c new_mfham.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c io_files.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c bandstructure.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c density_of_states.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c berry.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp  -c dielectric_response.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
gfortran -O3 -ffast-math -fbounds-check -fbacktrace -fopenmp -o tb90.x *.f90 -L/home/jose/apps/lapack-3.6.0 -l lapack -l blas 
