module inputs
use io_files  ! input and output files
implicit none
! electrons namelist

real (kind=8) :: filling=5.d-01,shift_fermi=0.d00
real (kind=8) :: extra_electrons=0.d00 ! number of extra electrons,
                                       ! added to the previous parameters
namelist /electrons/ filling,shift_fermi, extra_electrons
! kpoints namelist
integer :: nkpoints=20
real (kind=8) :: expand_bz =1.d00 ! expand the sampling
integer :: refine_kmesh_bands=1
integer :: refine_kmesh_dos=1
integer :: refine_kmesh_dielectric=1
integer :: refine_kmesh_denmat=1
namelist /kpoints/ nkpoints,refine_kmesh_bands,refine_kmesh_dos, &
                   refine_kmesh_dielectric,refine_kmesh_denmat, &
                   expand_bz
! convergence namelist
integer :: num_old_ham=1, max_ite = 1000
real (kind=8) :: smearing = 1.d-05,mix_coef=7.d-01
real (kind=8) :: max_scf_err = 1.d-06
real (kind=8) :: hubbard_scf = 1.d00
logical :: do_scf=.true.
logical :: is_collinear=.false.
logical :: ultrafast_mf=.false. ! calculate men field contribution
logical :: shift_to_zero=.true.
character (len=20) :: mean_field_operators = 'hubbard' ! mean field operators
character (len=20) :: smearing_type_scf = 'fermi-dirac' ! fermi dirac smearing
character (len=20) :: mean_field_matrix = 'ferro' ! mean field matrix
logical :: save_mean_field = .true.  ! save men field
real (kind=8) :: mean_field_amplitude = 1.d-01  ! amplitude of the mean field
! if generated by the program
namelist /scf_convergence/ num_old_ham,max_ite,smearing,mix_coef, &
                       max_scf_err,do_scf, shift_to_zero, &
                       mean_field_operators,hubbard_scf, &
                       mean_field_matrix,mean_field_amplitude, &
                       save_mean_field,smearing_type_scf, &
                       is_collinear,ultrafast_mf
! bands namelist
logical :: use_ewindow_bands=.false. ! use energy window in the bands
real (kind=8) :: emin_bands = -1.d00, emax_bands = 1.d00 !energy window in bands
character (len=20) :: bands_operators_option = 'default' ! operators for BC
logical :: do_bands=.true. ! perform bands calculation
character (len=20) :: klist_bands = 'default' ! klist for bands calculation
logical :: economic_memory_bands = .false. ! do not overflow memory
namelist /bands/ use_ewindow_bands,emin_bands,emax_bands, &
                 bands_operators_option, do_bands,klist_bands, &
                 economic_memory_bands
! dos namelist
character (len=20) :: dos_operators_option = 'default' ! operators for DOS
logical :: do_dos= .false.
! green still not implemented, for now still using
! the stupid method....
logical :: use_green = .true.  ! use green machinery (!NOT IMPLEMENTED)
logical :: do_ldos = .false. ! calculate LDOS
integer :: num_dos=30 ! number of intervals in DOS
logical :: use_ewindow_dos=.true. ! use energy window in the DOS
logical :: define_num_dos=.true. ! energies defined by number given
real (kind=8) :: emin_dos = -1.d00, emax_dos = 1.d00 ! energy window in DOS
logical :: autosmearing_dos=.true. ! automatically choose smearing
real (kind=8) :: smearing_dos = 1.d-02 ! smearing for DOS calculation
real (kind=8) :: estep_dos = 1.d-02 ! energy step for DOS calculation
namelist /dos/ num_dos,use_ewindow_dos,emin_dos,emax_dos,autosmearing_dos, &
               smearing_dos,estep_dos,define_num_dos,do_dos,do_ldos &
               ,dos_operators_option

! dielectric namelist
logical :: do_dielectric=.false. ! perform an RPA calculation
logical :: use_rpa=.true. ! perform an RPA calculation
integer :: num_ene_chi=30 ! number of intervals in chi
real (kind=8) :: ewindow_chi = 2.d-01 ! energy window to accept any contribution
real (kind=8) :: q_chi = 0.d00 ! q vector for dielectric response
real (kind=8) :: phi_chi = 0.d00 ! phi angle for dielectric response
real (kind=8) :: smearing_chi=1.d-03  ! smearing for w in chi
real (kind=8) :: temperature_chi=1.d-02  ! temperature for chi
real (kind=8) :: emin_chi = -1.d00, emax_chi = 1.d00
character (len=30) :: dielectric_type='global_all'  ! type of dielectric calculation
namelist /dielectric/ num_ene_chi,smearing_chi,emin_chi,emax_chi,q_chi, &
                      ewindow_chi, use_rpa, do_dielectric, dielectric_type, &
                      temperature_chi,write_full_chi,phi_chi
logical :: write_full_chi=.false. ! write the full chi matrix



! density matrix namelist
logical :: do_denmat=.false.  ! enter density matrix routines
real (kind=8) :: temperature_denmat=1.d-04  ! temperature for denmat
logical :: write_denmat=.false. ! write a file with the density matrix!
namelist /density_matrix/ do_denmat,write_denmat,temperature_denmat


! development namelist
logical :: show_debug=.false. ! general debuging information
logical :: show_diagonalization=.false. ! general debuging information
logical :: show_read_hamiltonian=.false. ! reading of the hamiltonian
namelist /development/ show_debug,show_diagonalization,show_read_hamiltonian


! berry namelist
logical :: do_berry=.false.  ! do berry calculation
logical :: has_tr=.false.     ! do Z2 calculation
real (kind=8) :: dk_becurv=1.d-02 ! Delta k for berry curvature calculation
character (len=30) :: klist_berry='default'  ! klist for berry, only in 2d
integer :: nkpoints_connection ! number of kpoints for berry connection
namelist /topology/ do_berry,dk_becurv,klist_berry,has_tr,nkpoints_connection







contains
! read the input file
  subroutine read_inputs   
  open(77,file="tb90.in")
  read(77,nml = electrons)  ! read electrons namelist
  read(77,nml = kpoints)  ! read kpoints namelist
  read(77,nml = bands)  ! read bands namelist
  read(77,nml = scf_convergence)  ! read convergence namelist
  read(77,nml = dos)  ! read DOS namelist
  read(77,nml = dielectric)  ! read dielectric namelist
  read(77,nml = density_matrix)  ! read density matrix namelist
  read(77,nml = topology)  ! topological quantities
  read(77,nml = development)  ! general debugging information
  close(77)
  end subroutine read_inputs
  


end module
