#!/usr/bin/python2


from __futute__ import print_function
import os

print("This script will install the dependencies to use CUDA acceleration")


def install(what):
  print "=========================="
  print "=========================="
  print "Installing ",what
  print "=========================="
  print "=========================="
  os.system("sudo apt-get install "+what)


packages = ["nvidia-cuda-toolkit"]

for p in packages:
  install(p)


print
print "All needed packages installed"

